name: vn_air_quality_weather
version: 1.0.0
config-version: 2

profile: vn_air_quality_weather
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages", "logs"]

models:
  vn_air_quality_weather:
    staging:
      +materialized: view
      +schema: staging
    dimensions:
      +materialized: table
      +schema: analytics
    facts:
      +materialized: table
      +schema: analytics
    marts:
      +materialized: table
      +schema: analytics
